### ISSUE TITLE
segmentation fault during travis build for rust executable

### ISSUE THREAD

**Issue by sagiegurari** [SimonKagstrom/kcov#207]
I looked at all previous issues for kcov with rust and I tried the solutions with no luck.
I have 2 projects. once actually works great (its a rust library) and the second seg fault (its a rust bin exe).

1. I install all the required dependencies
In log you can see:
````console
sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libcurl4-openssl-dev libelf-dev libdw-dev cmake gcc binutils-dev
````
and in travis yml
```yaml
before_install:
  - sudo apt-get update
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
````
2. Run the usual for loop over the files and run kcov on them.
but first i filter only the relevant files AND I also execute them first to see they are working fine.
````sh
for file in target/debug/deps/cargo_make*; do if "$file" ; then echo "Running $file"; kcov --verify --debug=4 --include-pattern=${TRAVIS_BUILD_DIR}/src/ "target/coverage" "$file" || true; fi; done
````
3. As you can see I also added the --verify as suggested in other issues and the --debug=4

I don't see any info on the core dump so i'm not sure what is the root cause.

you can look at the travis build log at:
https://travis-ci.org/sagiegurari/cargo-make/jobs/246654002

Hope you can help.
